# Generated by Django 6.1 on 2026-09-02 17:22

import django.core.validators
import django.db.models.deletion
import tuition.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionStudent',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('class_grade', models.CharField(blank=True, max_length=150)),
                ('guardian_contact', models.CharField(blank=True, max_length=255)),
                ('monthly_planned_classes', models.PositiveSmallIntegerField(default=12)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=8000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('start_date', models.DateField()),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('card_color', models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #4F46E5.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('description', models.TextField(blank=True)),
                ('active_month', models.CharField(default=tuition.models.current_month, max_length=7, validators=[django.core.validators.RegexValidator(message='Use YYYY-MM format.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Use YYYY-MM format.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tuition.tuitionstudent')),
            ],
            options={
                'ordering': ['-billing_month', '-paid_date'],
            },
        ),
        migrations.CreateModel(
            name='TuitionNote',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tuition.tuitionstudent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionMonthSnapshot',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Use YYYY-MM format.', regex='^\\d{4}-(0[1-9]|1[0-2])$')])),
                ('month', models.CharField(max_length=12)),
                ('year', models.PositiveSmallIntegerField()),
                ('planned_classes', models.PositiveSmallIntegerField()),
                ('completed_classes', models.PositiveSmallIntegerField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('closed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_history', to='tuition.tuitionstudent')),
            ],
            options={
                'ordering': ['-active_month'],
            },
        ),
        migrations.CreateModel(
            name='TuitionClassSlot',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_slots', to='tuition.tuitionstudent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TuitionMonthClassDate',
            fields=[
                ('id', models.CharField(default=tuition.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_dates', to='tuition.tuitionmonthsnapshot')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('user', 'snapshot', 'order'), name='tuition_unique_snapshot_class_order')],
            },
        ),
        migrations.AddIndex(
            model_name='tuitionstudent',
            index=models.Index(fields=['user', 'payment_status', 'student_name'], name='tuition_tui_user_id_912938_idx'),
        ),
        migrations.AddConstraint(
            model_name='tuitionstudent',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_planned_classes__gte', 1)), name='tuition_planned_classes_positive'),
        ),
        migrations.AddConstraint(
            model_name='tuitionstudent',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_salary__gte', 0)), name='tuition_salary_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tuitionpayment',
            constraint=models.UniqueConstraint(fields=('user', 'student', 'billing_month'), name='tuition_unique_student_billing_month'),
        ),
        migrations.AddConstraint(
            model_name='tuitionpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='tuition_payment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tuitionmonthsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'student', 'active_month'), name='tuition_unique_student_month_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='tuitionmonthsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('completed_classes__lte', models.F('planned_classes'))), name='tuition_snapshot_completed_lte_planned'),
        ),
        migrations.AddConstraint(
            model_name='tuitionmonthsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='tuition_snapshot_progress_valid'),
        ),
        migrations.AddConstraint(
            model_name='tuitionclassslot',
            constraint=models.UniqueConstraint(fields=('user', 'student', 'order'), name='tuition_unique_student_slot_order'),
        ),
        migrations.AddConstraint(
            model_name='tuitionclassslot',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='tuition_slot_order_positive'),
        ),
    ]
