# Generated by Django 6.1 on 2026-09-02 21:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='academic_routine_credit_nonnegative'),
        ),
    ]
