# Generated by Django 6.1 on 2026-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_routine_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattachment',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='assessmentattachment',
            name='google_drive_file_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='assessmentevent',
            name='google_calendar_event_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
