# Generated by Django 6.1 on 2026-09-21 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assessment_google_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'is_active', 'course_id'], name='academics_c_user_id_d1982f_idx'),
        ),
    ]
