# Generated by Django 6.1 on 2026-09-02 17:22

import django.core.validators
import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.CharField(default=finance.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=12000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DueBorrowRecord',
            fields=[
                ('id', models.CharField(default=finance.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('i_owe', 'I owe'), ('owed_to_me', 'Owed to me')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_settled', 'Partially settled'), ('settled', 'Settled')], default='open', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_borrow_records', to='finance.financeprofile')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=finance.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('mobile_banking', 'Mobile banking'), ('bank', 'Bank account'), ('cash', 'Cash'), ('card', 'Credit/debit card')], max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #4F46E5.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.financeprofile')),
            ],
            options={
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=finance.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Academic Materials', 'Academic materials'), ('Fees', 'Fees'), ('Internet & Bills', 'Internet and bills'), ('Transportation', 'Transportation'), ('Tuition Income', 'Tuition income'), ('Other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DueBorrowSettlement',
            fields=[
                ('id', models.CharField(default=finance.models.generate_id, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('due_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.dueborrowrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_borrow_settlements', to='finance.transaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='financeprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='finance_unique_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='financeprofile',
            constraint=models.CheckConstraint(condition=models.Q(('budget_limit__gte', 0)), name='finance_budget_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='dueborrowrecord',
            index=models.Index(fields=['user', 'status', 'due_date'], name='finance_due_user_id_53fc20_idx'),
        ),
        migrations.AddConstraint(
            model_name='dueborrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_due_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='dueborrowrecord',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__gte', 0), ('settled_amount__lte', models.F('amount'))), name='finance_due_settled_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'account_type'), name='finance_unique_user_account_type'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'category'], name='finance_tra_user_id_4f0d7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='dueborrowsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_settlement_amount_positive'),
        ),
    ]
