"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# StudySync keeps shared configuration in the monorepo root .env.
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-only-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Unconditionally allow Render domains and internal hosts
for domain in ['.onrender.com', 'studysync-jowq.onrender.com', 'localhost', '127.0.0.1']:
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'core.apps.CoreConfig',
    'academics.apps.AcademicsConfig',
    'tuition.apps.TuitionConfig',
    'finance.apps.FinanceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Supabase Auth / Django REST Framework


def normalize_supabase_url(value):
    """Return the project origin even if a REST endpoint URL was configured."""

    value = value.strip()
    if not value:
        return ''
    parsed = urlsplit(value)
    if parsed.scheme not in ('http', 'https') or not parsed.netloc:
        raise ValueError('SUPABASE_URL must be a valid HTTP(S) URL.')
    return urlunsplit((parsed.scheme, parsed.netloc, '', '', '')).rstrip('/')


SUPABASE_URL = normalize_supabase_url(os.getenv('SUPABASE_URL', ''))
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY', '')
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET', '')
SUPABASE_JWT_ISSUER = os.getenv(
    'SUPABASE_JWT_ISSUER',
    f'{SUPABASE_URL}/auth/v1' if SUPABASE_URL else '',
)
SUPABASE_JWT_AUDIENCE = os.getenv('SUPABASE_JWT_AUDIENCE', 'authenticated')
SUPABASE_JWKS_URL = os.getenv(
    'SUPABASE_JWKS_URL',
    f'{SUPABASE_JWT_ISSUER}/.well-known/jwks.json' if SUPABASE_JWT_ISSUER else '',
)
SUPABASE_JWT_ALGORITHMS = tuple(
    algorithm.strip()
    for algorithm in os.getenv('SUPABASE_JWT_ALGORITHMS', 'HS256,RS256,ES256').split(',')
    if algorithm.strip()
)
SUPABASE_JWT_LEEWAY_SECONDS = int(os.getenv('SUPABASE_JWT_LEEWAY_SECONDS', '30'))
SUPABASE_JWKS_CACHE_SECONDS = int(os.getenv('SUPABASE_JWKS_CACHE_SECONDS', '300'))
SUPABASE_JWKS_TIMEOUT_SECONDS = int(os.getenv('SUPABASE_JWKS_TIMEOUT_SECONDS', '10'))
SUPABASE_AUTH_TIMEOUT_SECONDS = int(os.getenv('SUPABASE_AUTH_TIMEOUT_SECONDS', '10'))

SYNC_MAX_DOCUMENTS_PER_REQUEST = int(os.getenv('SYNC_MAX_DOCUMENTS_PER_REQUEST', '50'))
SYNC_MAX_REQUEST_BYTES = int(os.getenv('SYNC_MAX_REQUEST_BYTES', str(2 * 1024 * 1024)))

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_ROUTINE_MODEL = os.getenv('GEMINI_ROUTINE_MODEL', 'gemini-2.5-flash')
GEMINI_ROUTINE_TIMEOUT_MS = int(os.getenv('GEMINI_ROUTINE_TIMEOUT_MS', '75000'))
GEMINI_ROUTINE_MAX_ATTEMPTS = int(os.getenv('GEMINI_ROUTINE_MAX_ATTEMPTS', '2'))
ROUTINE_IMAGE_MAX_BYTES = int(
    os.getenv('ROUTINE_IMAGE_MAX_BYTES', str(10 * 1024 * 1024))
)

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_CALENDAR_SCOPES = os.getenv('GOOGLE_CALENDAR_SCOPES', 'https://www.googleapis.com/auth/calendar.events')
GOOGLE_DRIVE_SCOPES = os.getenv('GOOGLE_DRIVE_SCOPES', 'https://www.googleapis.com/auth/drive.file')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SupabaseJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-google-token',
]

# Allow any Vercel deployment (preview/production) and all local ports
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.vercel\.app$",
    r"^http:\/\/(localhost|127\.0\.0\.1)(:[0-9]+)?$",
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]

for trusted_origin in ['https://*.vercel.app', 'https://studysync-jowq.onrender.com']:
    if trusted_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(trusted_origin)


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import sys

DATABASE_URL = os.getenv('DATABASE_URL')

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
elif DATABASE_URL:
    # Supabase requires an encrypted PostgreSQL connection. DATABASE_URL may
    # point to either the direct database host or a Supabase pooler.
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '60')),
            conn_health_checks=True,
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'True').lower()
            in ('true', '1', 'yes'),
        )
    }
else:
    # Keep SQLite available for local development without a configured .env.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (User uploads, attachments)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
